# This is a basic workflow to help you get started with Actions

name: Non-SMP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Charm++
    - name: build-charm++
      run: |
        git clone https://github.com/UIUC-PPL/charm.git
        cd charm
        git checkout v6.10.1
        ./build ChaNGa netlrts-linux-x86_64 -g -j4 --with-production --enable-error-checking

    # Prepare ParaTreeT build
    - name: prep-paratreet
      run: |
        git submodule init
        git submodule update
        cd utility/structures
        ./configure
        make

    # Build and test ParaTreeT
    - name: build-paratreet
      run: |
        export CHARM_HOME=$GITHUB_WORKSPACE/charm
        cd src
        make -j4 MAKE_OPTS="-DGROUP_CACHE"
        cd ../examples/
        make MAKE_OPTS="-DGROUP_CACHE"
        ./charmrun +p1 ./Gravity -f ../inputgen/1k.tipsy ++local -u 2
        ./charmrun +p4 ./Gravity -f ../inputgen/1k.tipsy ++local -u 2
        ./charmrun +p4 ./Gravity -f ../inputgen/1k.tipsy ++local -d sfc -u 2
        ./charmrun +p4 ./Gravity -f ../inputgen/1k.tipsy ++local -d kd -t kd -u 2
        ./charmrun +p4 ./Gravity -f ../inputgen/1k.tipsy ++local -d longest -t longest -u 2
        ./charmrun +p4 ./Gravity -f ../inputgen/1k.tipsy ++local -e -u 2
        ./charmrun +p1 ./SPH     -f ../inputgen/1k.tipsy ++local -u 2
        ./charmrun +p4 ./SPH     -f ../inputgen/1k.tipsy ++local -u 2
        ./charmrun +p4 ./SPH     -f ../inputgen/1k.tipsy ++local -d sfc -u 2
        ./charmrun +p4 ./SPH     -f ../inputgen/1k.tipsy ++local -d kd -t kd -u 2
        ./charmrun +p4 ./SPH     -f ../inputgen/1k.tipsy ++local -d longest -t longest -u 2
